### ISSUE TITLE
Module uses deprecated Puppet.newtype method instead of Puppet::Type.newtype

### ISSUE THREAD

**Issue by greigm** [example42/puppet-sysctl#8]
Seems to work fine with Puppet 4, except for the above deprecation warning.

The fix is:
```
--- /tmp/sysctl.rb      2016-01-06 14:17:18.352874870 +1300
+++ modules/sysctl/lib/puppet/type/sysctl.rb    2016-01-06 14:14:07.824725217 +1300
@@ -1,5 +1,5 @@
 module Puppet
-    newtype(:sysctl) do
+    Puppet::Type.newtype(:sysctl) do

         @doc = "Manages kernel parameters in /etc/sysctl.conf.  By default this will
                 only edit the configuration file, and not change any of the runtime
```

**Comment by greigm** [comment]
Wondered what was taking so long to fix this, then I noticed that it already IS fixed here! :)

It seems the version r10k is pulling from the forge is out of date. Is it possible to ensure these are in sync?

**Comment by alvagante** [comment]
I've pushed to the forge the updated version v2.0.18. Thanks
